### Assigment task 

- Inspect the dataset, e.g., check the ratio of the classes and discuss your findings.
- Divide the data into train and test sets.
- Perform scaling on the data.
- For each classifier, perform validation using Repeated k-Fold Cross-Validation (n_splits = 3, n_repeats = 10) on the train set.
    Choose the best metric, such as  Accuracy, Precision, Recall, etc., which can explain the task of  wine quality classification adequately.
    Evaluate the performance of the two classifiers based on the average and standard deviation of the chosen metric.
    Identify the best classifier based on its performance.
- Use the whole training set to build the final model using the best-performed classifier from the previous step. 
- Report the model's performance on the test set.
    Consider using the imbalanced-learn library or similar libraries to balance the scaled train set. Check the ratio of the classes and discuss your findings.
- Perform steps 4 to 5 using the balanced train set.
- Report the model's performance on the test set.
- Discuss your findings.

In [3]:
import pandas as pd

data = pd.read_csv("winequality-red.csv", sep=";")

data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [4]:
data.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [5]:
data['quality'].value_counts(normalize=True)

quality
5    0.425891
6    0.398999
7    0.124453
4    0.033146
8    0.011257
3    0.006254
Name: proportion, dtype: float64

### Dividing into train and test sets
---

- All columns except 'quality' are the *features* 
- 'quality' or y is what is to be predicted
- *test_size* is 20% of all the data is part of the testing space
- *stratify=y*: just keeps the data propotional in both data sub sets.

In [ ]:
from sklearn.model_selection import train_test_split
X = data.drop('quality', axis=1)
y = data['quality']

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42, stratify=y)

### Scaling the data
---
- *scaler* will compute mean and standard deviation
- *fit_transform* will standarize the values using *std* & *mean* using the formula **(x - mean) / std = x_scaled**
- *for test subset* it will not use mean and std from the training data not the test subset thus the usage of *.transform* i.e **no fitting.**

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

### Perfoming validation
---

**Metric:** F1-score 

**Classifiers**: Logistical Regression & Random Forrest

In [18]:
#  Repeated k-Fold Cross-Validation (n_splits = 3, n_repeats = 10) on the train set.

import numpy as np
from sklearn.model_selection import RepeatedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score

log_reg = LogisticRegression(
    solver='lbfgs', 
    max_iter=1000,
    random_state=2000
)

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=2000
)

random_seed = 2000

rkf = RepeatedKFold(n_splits=3, n_repeats=10, random_state=random_seed)

In [19]:
from sklearn.model_selection import cross_val_score

scores_log_reg = cross_val_score(
    log_reg,
    X_train_scaled,
    y_train,
    cv=rkf,
    scoring='f1_macro'
)

print("LogReg F1 scores (30 values):", scores_log_reg)
print("LogReg mean F1:", np.mean(scores_log_reg))
print("LogReg std F1:", np.std(scores_log_reg))

scores_rf = cross_val_score(
    rf,
    X_train_scaled,
    y_train,
    cv=rkf,
    scoring='f1_macro'
)
    
print("RF F1 scores (30 values):", scores_rf)
print("RF mean F1:", np.mean(scores_rf))
print("RF std F1:", np.std(scores_rf))

LogReg F1 scores (30 values): [0.33940378 0.2854759  0.28400821 0.2973304  0.29572826 0.35320289
 0.28254794 0.26835264 0.28212312 0.25510076 0.27805925 0.2762726
 0.25329545 0.27808874 0.27654851 0.36091147 0.2519742  0.28272906
 0.27246684 0.2629316  0.34812528 0.29016531 0.31601119 0.27280867
 0.25658243 0.29800452 0.31745332 0.28656598 0.26986639 0.26668773]
LogReg mean F1: 0.2886274139258715
LogReg std F1: 0.02894830340625973
RF F1 scores (30 values): [0.32994183 0.31151068 0.31770255 0.32100655 0.33536278 0.3129845
 0.31060595 0.33069032 0.31093315 0.33017979 0.32583175 0.30566416
 0.31310729 0.32842674 0.31972509 0.31379983 0.30431256 0.32022674
 0.33926267 0.32368006 0.32476431 0.33183536 0.3100965  0.30518782
 0.32058488 0.31551258 0.33990435 0.32325865 0.33293851 0.30466437]
RF mean F1: 0.3204567441177339
RF std F1: 0.010298812327744477

Based on this output **Random forrest** is the better classifier. It has a higher mean F1 and lower variance than Logistical regression

### Training and evaluating RF
---

In [23]:
rf.fit(X_train_scaled, y_train)

RandomForestClassifier(n_estimators=200, random_state=2000)

In [28]:
from sklearn.metrics import f1_score, accuracy_score, classification_report

y_test_pred = rf.predict(X_test_scaled)

test_f1 = f1_score(y_test, y_test_pred, average='macro')
test_acc = accuracy_score(y_test,y_test_pred)

print("Test macro F1:", test_f1)
print("Test accuracy:", test_acc) 

print("\nClassification report:\n")
print(classification_report(y_test, y_test_pred, zero_division=0))

Test macro F1: 0.40079845604463554
Test accuracy: 0.678125

Classification report:

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.71      0.76      0.74       136
           6       0.64      0.72      0.68       128
           7       0.71      0.50      0.59        40
           8       0.50      0.33      0.40         3

    accuracy                           0.68       320
   macro avg       0.43      0.39      0.40       320
weighted avg       0.65      0.68      0.66       320

### 7. Balancing the dataset
---

In [29]:
unique, counts = np.unique(y_train, return_counts=True)
for u, c in zip(unique, counts):
    print(f"Quality {u}: {c} samples")

Quality 3: 8 samples
Quality 4: 42 samples
Quality 5: 545 samples
Quality 6: 510 samples
Quality 7: 159 samples
Quality 8: 15 samples

In [32]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=2000)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train_scaled, y_train)

print(pd.Series(y_train_balanced).value_counts().sort_index())

quality
3    545
4    545
5    545
6    545
7    545
8    545
Name: count, dtype: int64

### Redoing steps 4-5 with balanced data set
---

In [34]:
scores_log_reg_bal = cross_val_score(
    log_reg,
    X_train_balanced,
    y_train_balanced,
    cv=rkf,
    scoring='f1_macro'
)

print("LogReg F1 scores (30 values):", scores_log_reg_bal)
print("LogReg mean F1:", np.mean(scores_log_reg_bal))
print("LogReg std F1:", np.std(scores_log_reg_bal))

scores_rf_bal = cross_val_score(
    rf,
    X_train_balanced,
    y_train_balanced,
    cv=rkf,
    scoring='f1_macro'
)
    
print("RF F1 scores (30 values):", scores_rf_bal)
print("RF mean F1:", np.mean(scores_rf_bal))
print("RF std F1:", np.std(scores_rf_bal))

LogReg F1 scores (30 values): [0.62336756 0.60703131 0.61647635 0.59822295 0.65048184 0.60429676
 0.61703143 0.6229986  0.6157682  0.63212489 0.6186584  0.61425645
 0.61767714 0.5987484  0.61495064 0.6356144  0.60924133 0.60825672
 0.62124828 0.6199639  0.60210032 0.62980557 0.61365406 0.62373425
 0.62004289 0.62240668 0.60653252 0.62225308 0.60127473 0.61743503]
LogReg mean F1: 0.6168551563816114
LogReg std F1: 0.011201928260124278
RF F1 scores (30 values): [0.86733954 0.83655926 0.87590759 0.85523904 0.86380738 0.85552423
 0.8753888  0.86273038 0.86273975 0.86238371 0.85286175 0.8642159
 0.84986177 0.83545081 0.86521377 0.85683139 0.86311294 0.8509008
 0.86704375 0.86067886 0.84775612 0.87151573 0.85112606 0.85856725
 0.84644397 0.87591544 0.87206393 0.87017224 0.84741329 0.85570454]
RF mean F1: 0.8593490005763716
RF std F1: 0.010549199992593135

Once again picking **Random forest** but with improvements 

**Logistic Regression**  
- Mean F1: 0.289 → 0.619  
- Std F1: 0.290 → 0.011  

**Random Forest**  
- Mean F1: 0.320 → 0.859  
- Std F1: 0.010 → 0.011

In [36]:
rf.fit(X_train_balanced, y_train_balanced)

y_test_pred = rf.predict(X_test_scaled)

test_f1 = f1_score(y_test, y_test_pred, average='macro')
test_acc = accuracy_score(y_test,y_test_pred)

print("Test macro F1:", test_f1)
print("Test accuracy:", test_acc) 

print("\nClassification report:\n")
print(classification_report(y_test, y_test_pred, zero_division=0))

Test macro F1: 0.362541574197856
Test accuracy: 0.621875

Classification report:

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.05      0.09      0.06        11
           5       0.75      0.67      0.71       136
           6       0.66      0.63      0.65       128
           7       0.57      0.62      0.60        40
           8       0.11      0.33      0.17         3

    accuracy                           0.62       320
   macro avg       0.36      0.39      0.36       320
weighted avg       0.65      0.62      0.64       320

| Model             | Test Accuracy | Test Macro-F1 |
| ----------------- | ------------- | ------------- |
| **Unbalanced RF** | **0.678**     | **0.401**     |
| **Balanced RF**   | 0.622         | 0.363         |


The unbalanced model performs better overall because the test set is dominated by majority classes.  
The balanced model attempts to account for minority classes, but since the test set contains very few of them, performance appears worse.